_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 23
                - 24
                - 55
            "4": 3.12.0
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
K:
    value: 5
L:
    value: 1
M:
    value: 5
T_end:
    value: 0.98
T_start:
    value: 0.95
algorithm:
    value: FedKDX
alpha:
    value: 1
alphaK:
    value: 1
auto_break:
    value: false
batch_num_per_client:
    value: 2
batch_size:
    value: 64
beta:
    value: 0
client_drop_rate:
    value: 0
dataset:
    value: SLEEP
device:
    value: cuda
device_id:
    value: "0"
dlg_eval:
    value: false
dlg_gap:
    value: 100
dr_learning_rate:
    value: 0
eta:
    value: 1
eval_gap:
    value: 1
feature_dim:
    value: 512
fine_tuning_epoch_new:
    value: 0
fine_tuning_epochs:
    value: 10
gamma:
    value: 0.1
generator_learning_rate:
    value: 0.005
global_rounds:
    value: 30
goal:
    value: test
head:
    value: |-
        Sequential(
          (0): Linear(in_features=784, out_features=128, bias=True)
          (1): ReLU()
          (2): Linear(in_features=128, out_features=64, bias=True)
          (3): ReLU()
          (4): Linear(in_features=64, out_features=12, bias=True)
        )
hidden_dim:
    value: 512
itk:
    value: 4000
join_ratio:
    value: 0.4
kl_weight:
    value: 0
lamda:
    value: 1
layer_idx:
    value: 2
learning_rate_decay:
    value: true
learning_rate_decay_gamma:
    value: 0.99
local_epochs:
    value: 4
local_learning_rate:
    value: 0.01
localize_feature_extractor:
    value: false
loss_fn:
    value: ce
max_len:
    value: 200
mentee_learning_rate:
    value: 0.01
model:
    value: |-
        BaseHeadSplit(
          (base): HybridBN(
            (conv1): Sequential(
              (0): Conv2d(3, 32, kernel_size=(1, 3), stride=(1, 1))
              (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              (2): ReLU()
              (3): MaxPool2d(kernel_size=(1, 2), stride=2, padding=0, dilation=1, ceil_mode=False)
            )
            (lstm): LSTM(32, 16, batch_first=True)
            (fc): Identity()
          )
          (head): Sequential(
            (0): Linear(in_features=784, out_features=128, bias=True)
            (1): ReLU()
            (2): Linear(in_features=128, out_features=64, bias=True)
            (3): ReLU()
            (4): Linear(in_features=64, out_features=12, bias=True)
          )
        )
momentum:
    value: 0.1
mu:
    value: 0
noise_dim:
    value: 512
num_classes:
    value: 12
num_clients:
    value: 15
num_new_clients:
    value: 0
optimizer:
    value: null
p_learning_rate:
    value: 0.01
plocal_epochs:
    value: 1
prev:
    value: 0
rand_percent:
    value: 80
random_join_ratio:
    value: false
save_folder_name:
    value: items
send_slow_rate:
    value: 0
server_epochs:
    value: 1000
server_learning_rate:
    value: 1
sigma:
    value: 1
tau:
    value: 1
time_select:
    value: false
time_threthold:
    value: 10000
times:
    value: 1
train_slow_rate:
    value: 0
vocab_size:
    value: 98635
wandb:
    value: true
